language: php

php:
  - 7.0

sudo: false

services:
  - postgresql

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --prefer-dist
  - make setup-db
  - php -S localhost:8000 web/app_dev.php &

script:
  - make unit-test
  - make test-ci
