imports:
    - { resource: security.yml }

parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: false }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        url: "postgresql://%DB_USER%:%DB_PASS%@%DB_HOST%/%DB_NAME%"
        charset:  UTF8
        types:
          tileset: 'Brainteaser\InfrastructureBundle\Persistence\Types\TileSetType'
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        mappings:
          Training:
              type: xml
              dir: "%kernel.root_dir%/../src/Brainteaser/InfrastructureBundle/Resources/config/doctrine/Training"
              alias: 'Training'
              prefix: 'Brainteaser\Domain\Training'
              is_bundle: false
          Exercise:
              type: xml
              dir: "%kernel.root_dir%/../src/Brainteaser/InfrastructureBundle/Resources/config/doctrine/Exercise"
              alias: 'Exercise'
              prefix: 'Brainteaser\Domain\Exercise'
              is_bundle: false
          ColoredTilesExercise:
              type: xml
              dir: "%kernel.root_dir%/../src/Brainteaser/InfrastructureBundle/Resources/config/doctrine/Exercise/ColoredTiles"
              alias: 'ColoredTilesExercise'
              prefix: 'Brainteaser\Domain\Exercise\ColoredTiles'
              is_bundle: false

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations
